version: '3.8'

services:
  api-lead-scoring:
    container_name: api-leads-scoring
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s